# ==============================================================================
# Стадия 1: Строитель (Builder)
# Здесь мы устанавливаем "тяжелые" зависимости для сборки
# ==============================================================================
FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS builder

WORKDIR /app

COPY pyproject.toml uv.lock /app/

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-install-project

COPY . .

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev

# ==============================================================================
# Стадия 2: Финальный образ
# Здесь мы собираем легкий образ для запуска приложения
# ==============================================================================
FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /app

# Копируем готовое виртуальное окружение из стадии "Строителя"
COPY --from=builder /app /app

ENV PATH="/app/.venv/bin:$PATH"
