# Generated by Django 5.2.8 on 2025-12-04 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChecklistSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Заголовок раздела"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел",
                "verbose_name_plural": "Справочник: Разделы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Название шаблона"),
                ),
            ],
            options={
                "verbose_name": "Шаблон",
                "verbose_name_plural": "Справочник: Шаблоны",
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_check",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "location_snapshot",
                    models.CharField(max_length=300, verbose_name="Участок (архив)"),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="Проверка завершена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет о проверке",
                "verbose_name_plural": "Журнал: Отчеты",
                "ordering": ["-date_check"],
            },
        ),
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(max_length=300, verbose_name="Раздел (архив)"),
                ),
                (
                    "criteria_text",
                    models.CharField(max_length=1000, verbose_name="Вопрос (архив)"),
                ),
                (
                    "criteria_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок (архив)"
                    ),
                ),
                (
                    "is_compliant",
                    models.BooleanField(
                        choices=[(True, "Соответствует"), (False, "Не соответствует")],
                        default=True,
                        verbose_name="Соответствие",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Результат пункта",
                "verbose_name_plural": "Результаты пунктов",
                "ordering": ["inspection", "section_name", "criteria_order"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Название участка"),
                ),
            ],
            options={
                "verbose_name": "Участок",
                "verbose_name_plural": "Справочник: Участки",
            },
        ),
        migrations.CreateModel(
            name="ViolationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="violations/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Фото нарушения",
                "verbose_name_plural": "Фото нарушений",
            },
        ),
        migrations.CreateModel(
            name="ChecklistCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=1000, verbose_name="Текст вопроса"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="checklists.checklistsection",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Критерий",
                "verbose_name_plural": "Справочник: Критерии",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="checklistsection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="checklists.checklisttemplate",
                verbose_name="Шаблон",
            ),
        ),
    ]
