# Generated by Django 5.2.8 on 2025-12-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistcriteria",
            name="text",
            field=models.CharField(max_length=1000, verbose_name="Текст вопроса"),
        ),
        migrations.AlterField(
            model_name="checklistsection",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Заголовок раздела"),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Название шаблона"),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="location_snapshot",
            field=models.CharField(max_length=300, verbose_name="Участок (архив)"),
        ),
        migrations.AlterField(
            model_name="inspectionitem",
            name="criteria_text",
            field=models.CharField(max_length=1000, verbose_name="Вопрос (архив)"),
        ),
        migrations.AlterField(
            model_name="inspectionitem",
            name="section_name",
            field=models.CharField(max_length=300, verbose_name="Раздел (архив)"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Название участка"),
        ),
    ]
