# Generated by Django 5.2.8 on 2025-12-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checklists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="inspector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Проверяющий",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="checklists.checklisttemplate",
                verbose_name="Использованный шаблон",
            ),
        ),
        migrations.AddField(
            model_name="inspectionitem",
            name="criteria_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="checklists.checklistcriteria",
                verbose_name="Ссылка на оригинал",
            ),
        ),
        migrations.AddField(
            model_name="inspectionitem",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="checklists.inspection",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="checklists.location",
                verbose_name="Участок",
            ),
        ),
        migrations.AddField(
            model_name="violationphoto",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="checklists.inspectionitem",
            ),
        ),
    ]
