# Generated by Django 5.2.8 on 2025-12-10 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inspection",
            unique_together={("template", "date_check")},
        ),
    ]
