# Generated by Django 5.2.8 on 2025-12-10 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0003_alter_inspection_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата назначения")),
                (
                    "inspection",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_item",
                        to="checklists.inspection",
                        verbose_name="Выполненный отчет",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначенный сотрудник",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checklists.checklisttemplate",
                        verbose_name="Шаблон проверки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в расписании",
                "verbose_name_plural": "График проверок",
                "ordering": ["date", "template"],
                "unique_together": {("template", "date")},
            },
        ),
    ]
