# Generated by Django 5.2.8 on 2025-12-10 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0004_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_swapped",
            field=models.BooleanField(default=False, verbose_name="Была замена"),
        ),
        migrations.CreateModel(
            name="SwapLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_date", models.DateField(verbose_name="Дата (была)")),
                ("target_date", models.DateField(verbose_name="Дата (стала)")),
                ("reason", models.TextField(verbose_name="Причина замены")),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_targets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="На кого заменили",
                    ),
                ),
            ],
            options={
                "verbose_name": "История замен",
                "verbose_name_plural": "Журнал: Замены",
                "ordering": ["-created_at"],
            },
        ),
    ]
