# Generated by Django 5.2.8 on 2026-01-29 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0005_schedule_is_swapped_swaplog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_locations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Начальник участка",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="masters",
            field=models.ManyToManyField(
                blank=True,
                related_name="mastered_locations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Мастера участка",
            ),
        ),
    ]
