# Generated by Django 5.2.8 on 2026-02-11 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0007_alter_location_manager_alter_location_masters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="deputy",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "deputy"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deputy_locations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заместитель начальника",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="senior_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "senior_master"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="senior_master_locations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Старший мастер",
            ),
        ),
    ]
