# Generated by Django 5.2.8 on 2026-03-02 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0008_location_deputy_location_senior_master"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="deputy",
        ),
        migrations.RemoveField(
            model_name="location",
            name="senior_master",
        ),
        migrations.AddField(
            model_name="location",
            name="deputies",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "deputy"},
                related_name="deputy_locations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заместители начальника",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="senior_masters",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "senior_master"},
                related_name="senior_master_locations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Старший мастер",
            ),
        ),
    ]
