# Generated by Django 5.2.8 on 2026-03-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "checklists",
            "0009_remove_location_deputy_remove_location_senior_master_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название маршрута"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок очереди"
                    ),
                ),
                (
                    "templates",
                    models.ManyToManyField(
                        related_name="routes",
                        to="checklists.checklisttemplate",
                        verbose_name="Входящие шаблоны",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маршрут обхода",
                "verbose_name_plural": "Справочник: Маршруты",
                "ordering": ["order"],
            },
        ),
    ]
