# Generated by Django 5.2.8 on 2026-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0010_inspectionroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistsection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("A", "Раздел А (Рабочее пространство)"),
                    ("B1", "Раздел В1 (ЭМО в цехах)"),
                    ("B2", "Раздел В2 (Оборудование)"),
                    ("C", "Раздел С (Участок в целом)"),
                    ("D", "Раздел D (ЭМО)"),
                    ("GENERAL", "Общий/Другой"),
                ],
                default="GENERAL",
                max_length=10,
                verbose_name="Тип раздела (для расчетов)",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="final_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Итоговый балл"
            ),
        ),
        migrations.AddField(
            model_name="inspectionitem",
            name="is_repeated_violation",
            field=models.BooleanField(
                default=False, verbose_name="Повторное нарушение"
            ),
        ),
        migrations.AddField(
            model_name="inspectionitem",
            name="section_type",
            field=models.CharField(
                default="GENERAL", max_length=10, verbose_name="Тип раздела (архив)"
            ),
        ),
    ]
