# Generated by Django 5.2.8 on 2026-03-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "checklists",
            "0011_checklistsection_section_type_inspection_final_score_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionSectionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(max_length=300, verbose_name="Название раздела"),
                ),
                (
                    "section_type",
                    models.CharField(max_length=10, verbose_name="Тип раздела"),
                ),
                ("score", models.FloatField(verbose_name="Балл за раздел")),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_scores",
                        to="checklists.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Балл за раздел",
                "verbose_name_plural": "Баллы за разделы",
            },
        ),
    ]
