# Generated by Django 5.2.8 on 2026-03-23 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0012_inspectionsectionscore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspectionsectionscore",
            options={
                "ordering": ["-date_check", "section_type"],
                "verbose_name": "Балл за раздел",
                "verbose_name_plural": "Баллы за разделы",
            },
        ),
        migrations.AddField(
            model_name="inspectionsectionscore",
            name="date_check",
            field=models.DateField(
                db_index=True,
                default=datetime.datetime(
                    2026, 3, 23, 9, 32, 1, 156839, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата проверки",
            ),
            preserve_default=False,
        ),
    ]
