# Generated by Django 5.2.8 on 2026-03-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0013_alter_inspectionsectionscore_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationDailyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Итоговый балл за день"
                    ),
                ),
                (
                    "calculation_details",
                    models.TextField(blank=True, verbose_name="Детали расчета"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checklists.location",
                        verbose_name="Участок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сводный балл участка",
                "verbose_name_plural": "Аналитика: Сводные баллы",
                "ordering": ["-date", "location"],
                "unique_together": {("location", "date")},
            },
        ),
    ]
