# Generated by Django 5.2.8 on 2026-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0014_locationdailyscore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspectionsectionscore",
            options={
                "ordering": ["-date_check", "section_type"],
                "verbose_name": "Балл за раздел",
                "verbose_name_plural": "Аналитика: Баллы за разделы",
            },
        ),
        migrations.AlterModelOptions(
            name="locationdailyscore",
            options={
                "ordering": ["-date", "location"],
                "verbose_name": "Сводный балл участка",
                "verbose_name_plural": "Аналитика: Сводные баллы участков",
            },
        ),
        migrations.AlterField(
            model_name="inspectionsectionscore",
            name="section_type",
            field=models.CharField(max_length=20, verbose_name="Тип раздела"),
        ),
        migrations.AlterUniqueTogether(
            name="inspectionsectionscore",
            unique_together={("inspection", "section_type")},
        ),
    ]
