# Generated by Django 5.2.8 on 2026-03-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0015_alter_inspectionsectionscore_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionitem",
            name="consecutive_violations",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Нарушений подряд"
            ),
        ),
    ]
