# Generated by Django 5.2.8 on 2026-03-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0016_inspectionitem_consecutive_violations"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="Дата"),
                ),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("work", "Рабочий день (например, суббота за понедельник)"),
                            ("off", "Доп. выходной (например, перенос понедельника)"),
                        ],
                        max_length=10,
                        verbose_name="Тип дня",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Описание (для админа)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Исключение календаря (Перенос)",
                "verbose_name_plural": "Справочник: Календарь (Переносы)",
                "ordering": ["-date"],
            },
        ),
    ]
