# Generated by Django 5.2.8 on 2026-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0017_calendaroverride"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendaroverride",
            name="day_type",
            field=models.CharField(
                choices=[("work", "Рабочий день"), ("off", "Доп. выходной")],
                max_length=10,
                verbose_name="Тип дня",
            ),
        ),
    ]
