# Generated by Django 5.2.8 on 2026-04-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0018_alter_calendaroverride_day_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время сдачи отчета"
            ),
        ),
    ]
