# Generated by Django 5.2.8 on 2026-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0019_inspection_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="swaplog",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("vacation", "Трудовой отпуск"),
                    ("trip", "Командировка"),
                    ("sick", "Больничный лист"),
                    ("other", "Другая причина"),
                ],
                default="other",
                max_length=20,
                verbose_name="Тип причины",
            ),
        ),
        migrations.AlterField(
            model_name="swaplog",
            name="reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Причина замены"
            ),
        ),
    ]
