# Generated by Django 5.2.8 on 2026-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0020_swaplog_reason_type_alter_swaplog_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleGeneratorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_user_id",
                    models.IntegerField(
                        default=0, verbose_name="ID последнего сотрудника"
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние генератора",
            },
        ),
    ]
