# Generated by Django 5.2.8 on 2026-05-25 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0021_schedulegeneratorstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectorRouteStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visits_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество назначений"
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверяющий",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checklists.inspectionroute",
                        verbose_name="Маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика инспектора по маршруту",
                "verbose_name_plural": "Статистика по маршрутам",
                "unique_together": {("inspector", "route")},
            },
        ),
    ]
