# Generated by Django 5.2.8 on 2025-12-05 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_perform_inspections",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если этот сотрудник должен участвовать в расписании.",
                verbose_name="Может проводить проверки",
            ),
        ),
        migrations.CreateModel(
            name="UserAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Начало")),
                ("end_date", models.DateField(verbose_name="Конец")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sick", "Болезнь"),
                            ("vacation", "Отпуск"),
                            ("other", "Другое"),
                        ],
                        default="vacation",
                        max_length=20,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Комментарий"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отсутствие сотрудника",
                "verbose_name_plural": "График отсутствий",
            },
        ),
    ]
