# Generated by Django 5.2.8 on 2026-01-21 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_can_perform_inspections_userabsence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон должен состоять только из цифр (от 9 до 15). Пример: 375445895647",
                        regex="^\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
