# Generated by Django 5.2.8 on 2026-01-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("worker", "Сотрудник"),
                    ("master", "Мастер участка"),
                    ("manager", "Начальник участка"),
                    ("admin", "Администратор"),
                ],
                default="worker",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
