# Generated by Django 5.2.8 on 2026-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("worker", "Сотрудник"),
                    ("manager", "Начальник участка"),
                    ("deputy", "Заместитель начальника"),
                    ("senior_master", "Старший мастер"),
                    ("master", "Мастер участка"),
                    ("production_chief", "Начальник производства"),
                    ("admin", "Администратор"),
                ],
                default="worker",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
