# Generated by Django 5.2.8 on 2026-03-17 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Используйте только русские буквы, пробел или дефис.",
                        regex="^[А-Яа-яЁё\\s\\-]+$",
                    )
                ],
                verbose_name="Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Используйте только русские буквы, пробел или дефис.",
                        regex="^[А-Яа-яЁё\\s\\-]+$",
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Используйте только русские буквы, пробел или дефис.",
                        regex="^[А-Яа-яЁё\\s\\-]+$",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
    ]
