# Generated by Django 5.2.8 on 2026-03-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_middle_name_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedCorporateEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Разрешенный Email"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Разрешенный Email",
                "verbose_name_plural": "Белый список Email",
            },
        ),
    ]
