# Generated by Django 5.2.8 on 2026-06-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vacation_end",
            field=models.DateField(blank=True, null=True, verbose_name="Конец отпуска"),
        ),
        migrations.AddField(
            model_name="user",
            name="vacation_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Начало отпуска"
            ),
        ),
    ]
