server {
    listen 80;
    server_name culture.miran.by;

    # Максимальный размер тела запроса (например, для загрузки файлов)
    client_max_body_size 20M;

    # Сжатие (ускоряет загрузку сайта)
    gzip on;
    gzip_disable "msie6";
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Логирование (опционально, можно выключить access_log для экономии места)
    # access_log /var/log/nginx/access.log;
    # error_log /var/log/nginx/error.log;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }


    location /static/ {
        alias /app/static/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        try_files $uri =404;
    }

    location /media/ {
        alias /app/media/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }

    # Заглушка для favicon, чтобы не спамить в логи бэкенда
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }
}
